# Generated by Django 3.2.6 on 2021-08-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Glance_Skills_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
