# Generated by Django 3.2.6 on 2021-09-01 16:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Glance_Skills_App', '0003_alter_extendeduser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=datetime.datetime(2021, 9, 1, 16, 16, 21, 395085, tzinfo=utc))),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=256)),
                ('image', models.ImageField(max_length=150, upload_to='images/categories/')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.DateTimeField(auto_created=datetime.datetime(2021, 9, 1, 16, 16, 21, 396088, tzinfo=utc))),
                ('project_name', models.CharField(max_length=256)),
                ('short_description', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=256)),
                ('likes', models.IntegerField()),
                ('image', models.ImageField(max_length=256, upload_to='images/project_images/')),
                ('video', models.FileField(upload_to='video/project_video/')),
                ('external_link', models.URLField(max_length=256)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Glance_Skills_App.projectcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projects_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.DateTimeField(auto_created=datetime.datetime(2021, 9, 1, 16, 16, 21, 396088, tzinfo=utc))),
                ('comments', models.TextField()),
                ('updated_by', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Glance_Skills_App.projects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
