# Generated by Django 3.2.6 on 2021-09-02 07:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Glance_Skills_App', '0004_projectcategory_projects_projects_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcategory',
            name='created_date',
            field=models.DateTimeField(auto_created=datetime.datetime(2021, 9, 2, 7, 47, 54, 352603, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='created_by',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects_comment',
            name='created_by',
            field=models.DateTimeField(auto_created=datetime.datetime(2021, 9, 2, 7, 47, 54, 355604, tzinfo=utc)),
        ),
    ]
