# Generated by Django 3.2.6 on 2021-09-09 15:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Glance_Skills_App', '0008_auto_20210908_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendeduser',
            old_name='phone_num',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='created_date',
            field=models.DateTimeField(auto_created=datetime.datetime(2021, 9, 9, 15, 49, 44, 892780, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projects_comment',
            name='created_by',
            field=models.DateTimeField(auto_created=datetime.datetime(2021, 9, 9, 15, 49, 44, 892780, tzinfo=utc)),
        ),
    ]
