# Generated by Django 3.2.6 on 2021-09-10 06:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Glance_Skills_App', '0009_auto_20210909_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='bio',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='profession',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='created_date',
            field=models.DateTimeField(auto_created=datetime.datetime(2021, 9, 10, 6, 41, 27, 460415, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projects_comment',
            name='created_by',
            field=models.DateTimeField(auto_created=datetime.datetime(2021, 9, 10, 6, 41, 27, 469411, tzinfo=utc)),
        ),
    ]
