# Generated by Django 3.2.6 on 2021-09-27 07:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Glance_Skills_App', '0010_auto_20210910_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='created_date',
            field=models.DateTimeField(auto_created=datetime.datetime(2021, 9, 27, 7, 10, 23, 602996, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projects_comment',
            name='created_by',
            field=models.DateTimeField(auto_created=datetime.datetime(2021, 9, 27, 7, 10, 23, 606020, tzinfo=utc)),
        ),
    ]
