# Generated by Django 3.2.6 on 2021-10-02 06:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Glance_Skills_App', '0011_auto_20210927_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='image',
            field=models.ImageField(null=True, upload_to='images/user_images/'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='created_date',
            field=models.DateTimeField(auto_created=datetime.datetime(2021, 10, 2, 6, 39, 17, 205700, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projects_comment',
            name='created_by',
            field=models.DateTimeField(auto_created=datetime.datetime(2021, 10, 2, 6, 39, 17, 205700, tzinfo=utc)),
        ),
    ]
