# Generated by Django 3.2.6 on 2021-10-06 02:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Glance_Skills_App', '0014_auto_20211006_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcategory',
            name='created_date',
            field=models.DateTimeField(auto_created=datetime.datetime(2021, 10, 6, 2, 57, 3, 877687, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projects_comment',
            name='created_by',
            field=models.DateTimeField(auto_created=datetime.datetime(2021, 10, 6, 2, 57, 3, 877687, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projects_comment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Glance_Skills_App.project'),
        ),
    ]
