# Generated by Django 3.2.6 on 2022-07-16 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Glance_Skills_App', '0020_auto_20211225_0956'),
        ('Glance_Skills_App', '0020_auto_20220410_1259'),
    ]

    operations = [
    ]
