# Generated by Django 3.2.6 on 2022-07-18 12:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Glance_Skills_App', '0021_merge_0020_auto_20211225_0956_0020_auto_20220410_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='image',
            field=models.ImageField(default='/static/img/defaultuser.jpg', null=True, upload_to='images/user_images/'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='created_date',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 7, 18, 12, 20, 38, 28322, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projects_comment',
            name='created_by',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 7, 18, 12, 20, 38, 29923, tzinfo=utc), auto_now_add=True),
        ),
    ]
