# Generated by Django 3.2.6 on 2022-07-18 12:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Glance_Skills_App', '0023_auto_20220718_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='image',
            field=models.ImageField(default='/user/defaultuser.jpeg', null=True, upload_to='images/user_images/'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='created_date',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 7, 18, 12, 47, 14, 498567, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projects_comment',
            name='created_by',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 7, 18, 12, 47, 14, 500132, tzinfo=utc), auto_now_add=True),
        ),
    ]
