# Generated by Django 3.2.6 on 2022-07-18 12:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Glance_Skills_App', '0025_auto_20220718_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='image',
            field=models.ImageField(default='/images/user_images/defaultuser.jpeg', null=True, upload_to='images/user_images/'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='created_date',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 7, 18, 12, 52, 48, 470600, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projects_comment',
            name='created_by',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 7, 18, 12, 52, 48, 472263, tzinfo=utc), auto_now_add=True),
        ),
    ]
