# Generated by Django 3.2.6 on 2022-07-20 15:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Glance_Skills_App', '0026_auto_20220718_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcategory',
            name='created_date',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 7, 20, 15, 46, 50, 863300, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projects_comment',
            name='created_by',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 7, 20, 15, 46, 50, 864297, tzinfo=utc), auto_now_add=True),
        ),
    ]
